component added
cwipedia-in/training.cwipedia pull request #5
Opened 2022-10-08 15:48 UTC by amansingh1373

2022-10-08 19:32 UTC, 0shivamh requested changes

2022-10-08 19:32 UTC, 0shivamh commented on src/Components/features.components.js
> +                    <FontAwesomeIcon icon={faCircle} />
change this icon to Star

2022-10-09 12:33 UTC, amansingh1373 commented
@0shivamh  kindly take a look at it

2022-10-10 08:31 UTC, 0shivamh commented
LGTM

> @0shivamh kindly take a look at it

2022-10-10 08:32 UTC, merged